include_recipe "../cookbooks/sshd/default.rb"
include_recipe "../cookbooks/campaign/campbt.rb"
include_recipe "../cookbooks/campaign/java.rb"
include_recipe "../cookbooks/campaign/oracle-client.rb"
include_recipe "../cookbooks/campaign/postgresql.rb"
